version: '3.9'
services:
  auth-api-db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-api
    volumes:
      - ./pgdata:/var/lib/postgresql/auth-api-db
